makhidkarun/traveller_pyroute

- PyRoute/Star.py
- Tests/StarTests.py
Memoise hash calculation of Star objects to speed up route generation.
- Star objects seem immutable once route generation starts, so calculate hash code once and cache it, rather than on each and every call.
Add hash-equality check to Star __eq__ method.
- Take advantage of the hash-calc speedup and check that two Star objects have the same hash code, before proceeding to the full key-equality check.  If hash codes are not equal, the two objects cannot be equal, so avoid pointlessly incurring the full key-equality cost.
As a result of those changes, I've been able to reduce route-generation time for Reft + the four orthogonally adjacent sectors on a 4x4.1 Ghz Intel i7-6700k by 38% - from 135 seconds to 83 seconds.  Memoising hash calculation saved ~33% of original route-gen time, while …
> Memoise hash calc

- .gitignore
- PyRoute/Galaxy.py
- PyRoute/Star.py
- Tests/testStar.py
- Tests/testTradeCode.py
Make the test files easier to discover to run with unittest by renaming them to the conventional `test*.py` format.
In the process of doing that, I tripped over an apparent omission when creating a Sector object - eg, for the star Irkigkhan (Core 0103), it was being printed in the logger as:
`ERROR - Irkigkhan (ore 0103)-C9C4733-9 Calculated "Fl" not in trade codes ['Wa']`
After what I presume is the fix, that same line now displays as:
`ERROR - Irkigkhan (Core 0103)-C9C4733-9 Calculated "Fl" not in trade codes ['Wa']`
I'm not sure what should be happening with PyRoute/DrawArcsTest.py, so I've left it alone - should it also be moved into the Tests folder?
> Square up tests

- PyRoute/TradeCodes.py
- Tests/testStar.py
- Tests/testTradeCode.py
The test suite seems to have rotted since the jump to Python 3, so this PR fixes the bit rot and gets test suite running clean. This is a necessary (but not sufficient) precondition to enable per-pull-request CI setup.
In addition, to reduce visual clutter during test runs, I directly asserted the expected logger results in testCodeCheckFails.
> Fix up tests to match Python 3

- PyRoute/Galaxy.py
- Tests/testGalaxy.py
See #19 for specific case that tumbled this.
It looks like, somewhere along the way, rimward and coreward neighbouring sectors got transposed - this PR fixes that and adds two fairly simple regression tests to verify this stays fixed.
> Verify sector ordering

- PyRoute/FontLayer.py
- PyRoute/SubsectorMap2.py
- PyRoute/wikistats.py
Running PyRoute on a Fedora box, when it was originally written on a Ubuntu box, has rumbled some Ubuntu-specific assumptions as to font locations.  Running PyRoute in an IDE, to debug and profile it, rumbled an implicit assumption that the current working directory is the project root dir - that assumption didn't necessarily hold.
To fix the working dir assumption, I've tweaked the wiki template class to supply the _absolute_ base dir for the wiki templates.
To encapsulate the font-location assumptions, I've added a dirt-simple adapter class (named, with much originality, FontLayer) that translates the four font files used in SubsectorMap2.py into the underlying absolute paths on Ubuntu or Fedora.  I've structured FontLayer to make it very easy to add additional mappings for existing …
> Fix wiki template and font file paths

- PyRoute/Star.py
- PyRoute/TradeCalculation.py
After digging around, I found a couple of places where unneeded computation can be trimmed.  For reference, times reported are under the PyCharm 2020 built-in profiler on the same 4x4.1 Ghz Intel i7-6700k that I did PR #3 on.  The relative changes are probably more important than the absolute times.
The first, and biggest, gain was using the structure of the galaxy.stars graph.  Due to, frinstance, small connected clusters deep in Rift sectors (such as the Islands, the mid-Rift cluster in Riftspan Reaches, to name two), it seems extremely unlikely that the resulting graph is fully connected (fancy term for any node (star, in our case) being reachable from any other).
Any pathfinding attempt between two different components is doomed to failure - by the graph structure, _no such path …
> Trim unneeded computation

- PyRoute/SubsectorMap2.py
I got tired of full-up Charted Space runs falling at one of the last hurdles, namely subsector map generation (especially in Angfutsag).  This was especially annoying if I was trying to _profile_ said run to sniff out hotspots.
With a null or blank subsector name, `SubsectorMap2.close()` was trying to close a file named `.png` - this caused PIL to have a major conniption, as it saw that as a regular dotfile without a determinable extension.  Thus, it blew up with `ValueError: unknown file extension: `.
Turns out the fix (at least, the one I found) was quite simple - if the supplied subsector name is null or blank, _assign_ a well-defined default subsector name.  I've simply gone with `{sector name}-{subsector position}` for the moment.
> Assign default subsector names if needed

- PyRoute/TradeCalculation.py
- Tests/testTradeCalculation.py
Start implementing the during-generation invariants I listed here: https://github.com/makhidkarun/traveller_pyroute/issues/16#issuecomment-991689038
@tjoneslo , et al, a program's invariants are like a building's foundations - you need them to build a solid building (or program). Invariants describe conditions that must _always_ hold for your program to have a chance of running correctly.
The existing code was only generating at most one of the forward or reverse routes from star A to star B, so I enforced that behaviour.
The positive-edge-cost invariant actually applies to A* pathfinding itself, not PyRoute directly, but (as you can see in the commit), enforcing it saves a lot of hassle.
> Start enforcing during-pathfinding invariants

- requirements.txt
Fixes https://github.com/makhidkarun/traveller_pyroute/issues/22.
Note that while I ran `pip install -r requirements.txt` I couldn't figure out how to run the unit tests, so this should be tested before merging.
Also FYI I could help you switch to [Poetry](https://python-poetry.org) for package management if you'd like. The main advantage is that Poetry enables bundling otherwise conflicting versions of dependencies, and it also streamlines installation to the user's path as well as publishing to PyPI.
> Update requirements to wikitools3

- .gitignore
- PyRoute/Galaxy.py
- PyRoute/Pathfinding/astar.py
- PyRoute/Star.py
- PyRoute/TradeCalculation.py
As pathfinding is the biggest part of most runs, it actually paid off adding a custom A* implementation, derived from the networkx one, that made assumptions better fitting pyroute (rather than general use).
The custom pathfinder also aggressively prunes blind alleys, dead ends, and upper-bound-busters before spending too much time on them.
Over a 12 sector testbed (Reft Sector, Trojan Reach, Deneb, Gushemege, Verge, Riftspan Reaches, Touchstone, Hlakhoi, 
Corridor, Vland, Dagudashaag, Zarushagar), totalling 4,117 stars:
As at https://github.com/makhidkarun/traveller_pyroute/commit/076f1a130d3b2754de300731422cdeeb9e18aede :
Overall took 22 min 16 sec, (1336 s) with pathfinding occupying 18 min 17 sec (1097 s), or 82% of total.
As at "Sort neighbours after filtering", same testbed ( I …
> Add custom A* pathfinding implementation

- PyRoute/downloadsec.py
- sectorlist.txt
As it says on the tin, update the full-orchestra sector list to reflect new sectors that have landed since 2014(?)
I've also added some basic retry logic to downloadsec.py, where it retries _once apiece_ to download a given URL upon encountering either an HTTPError or a URLError.  This should fix #45 .
> Update sector list

- .gitignore
- PyRoute/Calculation/TradeCalculation.py
- PyRoute/Calculation/TradeMPCalculation.py
- PyRoute/DeltaDebug/DeltaGalaxy.py
- PyRoute/DeltaDebug/DeltaReduce.py
- PyRoute/Galaxy.py
- PyRoute/Pathfinding/ApproximateShortestPathTreeZeroCaching.py
- PyRoute/Pathfinding/astar.py
- PyRoute/Position/Hex.py
- PyRoute/StatCalculation.py
- PyRoute/TradeBalance.py
- PyRoute/WikiUploadPDF.py
- PyRoute/route.py
- Tests/Outputs/testHexMap.py
- Tests/Pathfinding/testApproximateShortestPathTree.py
- Tests/Pathfinding/testApproximateShortestPathTreeRegressions.py
- Tests/Pathfinding/testAstarIndexes.py
- Tests/Pathfinding/testTradeCalculationLandmarks.py
- Tests/baseTest.py
- Tests/testAllyGenBorders.py
- Tests/testDeltaGalaxy.py
- Tests/testDeltaReduce.py
- Tests/testTradeCalculation.py
- pyproject.toml
- readme.md
This PR adds in a multiprocessing-powered variant of trade calculation that can cut at least 50% off overall running times on bigger setups (implist, full-orchestra).
As with any performance tuning step, it makes a tradeoff - taking more RAM and cpu time (running in parallel) to reduce overall wallclock time.
> Add trade multi-processing variant

- PyRoute/DeltaDebug/DeltaDebug.py
- Tests/baseTest.py
- Tests/testDeltaDebug.py
- requirements.txt
Update the Galaxy construction in delta debugging to match the new API.
Add pytest-console-scripts as requirement to enable scripts (such as DeltaDebug itself) to be run inside tests.
Add empty-list delta debugging test to keep an eye on the delta debugging setup and close test-coverage hole that let it break silently in the first place.
> Fix delta debugging

- PyRoute/Position/Hex.py
- Tests/Hypothesis/Position/testHexHypothesis.py
- Tests/Position/testHex.py
Add axial_to_hex conversion (functional inverse of hex_to_axial);
Add axial_to_sector conversion (dumping out within-sector co-ords only);
Add hypothesis tests to verify both new conversions
> Add hypothesis tests to Hex

- PyRoute/SystemData/StarList.py
- Tests/Hypothesis/testStarList.py
As at the status quo, missing/wonky star sizes ended up heaved out the window.
Two _specific_ cases (motivating this PR) I tripped over from the M1105 Travmap data (turned out they were the _only_ ones in the M1105 data as at Nov 2023) are:
```
Wrenton 1901: G7 M4 V
Blaskon 2828: M5 IC
```
After checking with @inexorabletash , he agreed (presuming the QWERTY keyboard layout) that IC is most likely a typoed form of IV.  For missing sizes, he agreed with my suggestion to play the odds and assume a star size of V.
The two motivating examples fall out after those changes as:
```
Wrenton 1901: G7 V M4 V
Blaskon 2828: M5 IV
```
These two _particular_ cases have been fixed in Travmap, but I want to harden PyRoute against similar, undetected, cases, such as in other milieux, and future …
> Handle missing/wonky star sizes

- PyRoute/Inputs/ParseStarInput.py
Previously, any four digits would match the position sub-match. This was done for simplicity's sake, and has worked brilliantly up until now.
With the rest of parsing getting belted, position has fallen behind a bit.  The highest valid column in a position is 32, and highest valid row is 40.  Thus, a tens column digit of 4+ is prima facie nonsensical, likewise a tens row digit of 5+.
Since we can catch those at the starline regex stage, do so.
> Tighten starline regex's position sub-match

- PyRoute/Star.py
- PyRoute/SystemData/UWP.py
- PyRoute/SystemData/Utilities.py
- Tests/Hypothesis/testUWP.py
Government type is used in `Star.calculateTCS()` twice to determine both budget and ship capacity.
Status quo permits any character matching `[0-9A-Za-z\?]`, which can be on a collision course to a key error, when the putative government type is not referenced in the tax rate array (shifted to `Utilities` for ease of use and dodging circular imports).
The fix is rather simple - when building the UWP object, require its putative government code to be a key in the tax rate array.  Leaving the UWP regex as-is simplifies the case of adding a government type - just add it to the tax rate array and move on.
> Constrain UWP gov types

- PyRoute/TradeCodes.py
- Tests/Hypothesis/testTradeCodes.py
Add the machinery to canonicalise trade codes according to T5 rules against the starline's current UWP.
This will ultimately hook into full-starline canonicalisation, useful both for delta debugging and cleaning up wonky sector data.
> Canonicalise trade codes

- PyRoute/Calculation/TradeCalculation.py
- PyRoute/Galaxy.py
- PyRoute/Pathfinding/DistanceBase.py
- PyRoute/Pathfinding/astar_numpy.py
- Tests/Pathfinding/testRouteLandmarkGraph.py
- Tests/testTradeCode.py
Benefiting from tightened _lower_ bounds in A* pathfinding only requires an _admissible_ heuristic - one that never over-estimates cost to the target from some current node.
Benefiting from tightened _upper_ bounds, however, requires that the heuristic be _consistent_, not merely admissible.  A consistent heuristic is an admissible heuristic such that, over all nodes K, for a given node N and each successor P of N, the heuristic value h(N) is not greater than the sum of the cost of the edge from N to P, c(N, P), and the heuristic value at P, h(P).  In other words:
c(N, P) >= h(N) - h(P)
As at the status quo, the bulk heuristic was the case-wise maximum of the following subheuristics:
- approx-shortest-path
- min-edge-cost
- historic path _distances_
The first two subheuristics are …
> Preheat upper pathfinding bounds

- PyRoute/Calculation/TradeCalculation.py
- PyRoute/Pathfinding/ApproximateShortestPathForestUnified.py
- PyRoute/Pathfinding/LandmarkSchemes/LandmarksTriaxialExtremes.py
- PyRoute/Pathfinding/astar_numpy.py
- Tests/Pathfinding/testApproximateShortestPathForest.py
Before this PR, bulk lower-bound calculations in the approx-SP forest involved spinning through each approx-SP tree the forest contained, making the bulk lower-bound call on the tree, and then collecting and reducing the results.
Even though bulk heuristic is now only called once per pathfinding run, its runtime will become an increasing problem (and chunk of overall pathfinding runtime) as:
- tighter upper and lower bounds are generated and used, leading to fewer nodes queued and expanded;
- as more landmarks are added to each connected component (which also tightens lower bounds, causing a double whammy).
Obvious solution is obvious - transform the sequence of N method calls into one such call, leaning on numpy to manipulate the unified distances array in bulk.
Pulling all the distance …
> Unify approx-SP forest

- .github/workflows/python-package.yml
- PyRoute/Calculation/RouteCalculation.py
- PyRoute/Calculation/TradeCalculation.py
- PyRoute/Pathfinding/ApproximateShortestPathTreeDistanceGraph.py
- PyRoute/TradeCodes.py
- Tests/Pathfinding/testApproximateShortestPathTree.py
- Tests/testTradeCalculation.py
Speed up trade graph generation by increasing the amount of work not done:
Memoise things that are hit repeatedly in tight loops:
1.  Whether systems are agricultural, or need an agricultural partner;
2. Likewise for industrial systems/partners;
3. BTN distance penalties;
4. Maximum distance values given endpoint WTNs;
Filter distance-busts from _candidate_ route list up front, rather than spinning through the entirety of the **RouteCalculation.generate_base_routes()** malarkey.
And finally, filter out more doomed route candidates:
L153 of status-quo **RouteCalculation** quoth:
`max_btn = (min(star1.wtn, star2.wtn) * 2) + 1`
This combines with the specified minimum route BTN to imply (letting largest doubled-WTN that can't support a trade route be W):
```
min_route_btn > W * 2 + 1 …
```
> Speed up jump-graph generation

- PyRoute/DataClasses/ReadSectorOptions.py
- PyRoute/DeltaStar.py
- PyRoute/DrawArcsTest.py
- PyRoute/Galaxy.py
- PyRoute/Inputs/ParseStarInput.py
- PyRoute/Outputs/GraphMap.py
- PyRoute/Outputs/SubsectorMap2.py
- PyRoute/Star.py
- PyRoute/TradeCodes.py
- PyRoute/WikiCreateWorlds.py
- PyRoute/route.py
I got tired of 3 megabytes+ of crap filling up the logs of full-orchestra charted space runs, which I generally have to leave running overnight.
A shufti showed ~60% of those on the Dec 23, 2023 TravellerMap data were invalid/missing population trade code complaints (including the infamous 'Ba Lo Ni' combo on actually-barren systems).
Thus, I added a fix_pop debug option, to fix those problems as their respective starlines were parsed, which did the following:
approx 25,700 parsing complaints as at status quo;
approx 10,770 parsing complaints as at this PR;
that giving a 58.0% net reduction in the number of complaints filling up the logs in a full-orchestra run, and (big surprise) reducing crap buildup by ~1.8 megabytes.
The remaining trade-code related complaints (using the …
> Add debug option to fix pop-based trade codes in flight

- PyRoute/Calculation/TradeCalculation.py
- PyRoute/Galaxy.py
- PyRoute/Pathfinding/LandmarkSchemes/LandmarksTriaxialExtremes.py
- PyRoute/Pathfinding/astar_numpy.py
- Tests/Pathfinding/testApproximateShortestPathForest.py
- Tests/Pathfinding/testAstarNumpy.py
- Tests/Pathfinding/testTradeCalculationLandmarks.py
Bunch of little tune-ups to speed up astar routine.
Under profiling **astar_path_numpy**, total pathfinding time over Reft + 4 orthogonals went from 3 min 0 sec (180 sec) to 2 min 27 sec (147 sec) - 18.3% speedup.
> Tune Astar

- pyproject.toml
- requirements.txt
As per https://numpy.org/devdocs/release/2.0.0-notes.html , bump numpy dep to 2.0+ and (surprisingly) find no obsolete-call blowups to fix.
> Bump numpy to 2.0

- PyRoute/DeltaPasses/Canonicalisation.py
- PyRoute/DeltaStar.py
- PyRoute/Star.py
- Tests/Hypothesis/testStar.py
- Tests/testDeltaPasses.py
Add method to canonicalise a given Star object - "canonical" in this case being with respect to the checks that already exist when reading a given starline in.
This pulls the star canonicalisation bits out of the mess that is #70 and into a form much more easily reviewable.
> Add star canonicalisation

- PyRoute/DeltaDebug/DeltaDebug.py
- PyRoute/DeltaPasses/AllegianceReducer.py
- PyRoute/DeltaPasses/SectorReducer.py
- PyRoute/DeltaPasses/SingleLineReducer.py
- PyRoute/DeltaPasses/SubsectorReducer.py
- PyRoute/DeltaPasses/TwoLineReducer.py
- Tests/testDeltaPasses.py
- Tests/testDeltaReduce.py
Expand breaches found somewhat more aggressively during delta debugging.
Breach reduction starts with finding some reduction in another pass, then (either forwards or backwards), iteratively removing 1, 2, 4, 8, etc lines until the removed lines were interesting.
First, widen breaches both forward and backwards in single-line reduction.
Second, widen breaches both forward and backwards in subsector-level reduction.
Third, write out still-interesting sector files at end of both allegiance and sector level reduction.
> Expand breach reduction when delta debugging

- PyRoute/DeltaStar.py
- PyRoute/Inputs/ParseStarInput.py
- PyRoute/Star.py
- PyRoute/TradeCodes.py
- Tests/Hypothesis/Inputs/testHypothesisStarlineParser.py
- Tests/Hypothesis/testDeltaStar.py
- Tests/Hypothesis/testStar.py
Big one here is making individual-star canonicalisation _idempotent_ - canonicalising a given star _once_ and _more than once_ has the same net effect.
It allows the user to be confident that they will only need to canonicalise a given star once, and it won't hurt anything if it's canonicalised more than once.
> Wring out individual-star canonicalisation

- PyRoute/Errors/MultipleWPopError.py
- PyRoute/Inputs/ParseStarInput.py
- PyRoute/TradeCodes.py
- Tests/Hypothesis/testTradeCodes.py
Much like the previous PR ( #132 ) , wring out trade code parsing according to the following property, with HypoFuzz (13 h 0 min, 5.49M inputs without new path for first batch (up to `[Assume out not-in-allowed-list well-formed failures]` inclusive), 10 h 30 min, 5.69M inputs without new path for second batch  (up to `Blow up on explicit homeworld-code W-pop counts` inclusive):
Given a string conforming to the trade code part of the `ParseStarInput.starline` regex (in practice, _any_ characters), it either:
1.  Is cleanly parsed by the `TradeCodes` constructor; or
2. Blows up with a subclass of `ValueError` exception.
Given 1 above, I'm also checking that feeding the string representation of a `TradeCodes` object into the constructor results in a new `TradeCodes` object with the _same_ …
> Wring out trade codes parsing

- PyRoute/DeltaDebug/DeltaReduce.py
- PyRoute/DeltaPasses/AllegianceReducer.py
- PyRoute/DeltaPasses/SectorReducer.py
- PyRoute/DeltaPasses/SingleLineReducer.py
- PyRoute/DeltaPasses/SubsectorReducer.py
- PyRoute/DeltaPasses/TwoLineReducer.py
- PyRoute/DeltaPasses/WithinLineReducer.py
- PyRoute/Nobles.py
- PyRoute/SpeculativeTrade.py
- PyRoute/Star.py
- PyRoute/TradeCodes.py
I was working on some pathfinding tweaks when (surprise surprise) running over the imperial sector list blew up.
The first couple of times, delta debugging from the 32 sector imperial list wasn't _too_ annoying, but that changed with the third and later detonations.  Those somewhat quickly blew up with out-of-memory errors - on a box with 32 GB of physical RAM.
After some investigation between detonations, and liberal use of tracemalloc, turns out the Galaxy variable isn't getting cleaned up between iterations.  Tackling that, and some other things, reduced the largest memory allocation at the end of the SubsectorReduce pass by just under 3.8 fold, with similar reductions elsewhere.
Due to the delta debugging runs blowing up, I also changed all delta debugging passes to write out the …
> Reduce delta debug memory use

- PyRoute/DeltaDebug/DeltaDebug.py
- PyRoute/DeltaDebug/DeltaDictionary.py
- PyRoute/DeltaDebug/DeltaReduce.py
- PyRoute/DeltaPasses/AllegianceReducer.py
- PyRoute/DeltaPasses/AuxiliaryLineReduce.py
- PyRoute/DeltaPasses/CapitalLineReduce.py
- PyRoute/DeltaPasses/FullLineReduce.py
- PyRoute/DeltaPasses/ImportanceLineReduce.py
- PyRoute/DeltaPasses/SectorReducer.py
- PyRoute/DeltaPasses/SingleLineReducer.py
- PyRoute/DeltaPasses/SubsectorReducer.py
- PyRoute/DeltaPasses/TwoLineReducer.py
- PyRoute/DeltaPasses/WithinLineReducer.py
- PyRoute/Nobles.py
- PyRoute/Star.py
- PyRoute/StatCalculation.py
- PyRoute/TradeCodes.py
- Tests/Pathfinding/testStatCalcRegression.py
- Tests/testDeltaDictionary.py
Following up #143 , here's some more tweaks to further reduce memory use, clean up internals of delta debugging, and spit out intermediate results (ie, sector files) more frequently.
Unlike #143 , this isn't one major focused chunk, but a collection of smaller chunks.
> Reduce delta debug mem use

- PyRoute/DeltaDebug/DeltaDictionary.py
- PyRoute/DeltaDebug/DeltaGalaxy.py
- PyRoute/DeltaDebug/DeltaReduce.py
- PyRoute/DeltaPasses/BeyondLineReducer.py
- PyRoute/DeltaPasses/NBZLineReduce.py
- PyRoute/DeltaPasses/SectorReducer.py
- PyRoute/DeltaPasses/SingleLineReducer.py
- PyRoute/DeltaPasses/SubsectorReducer.py
- PyRoute/DeltaPasses/TwoLineReducer.py
- PyRoute/DeltaPasses/WithinLineReducer.py
- PyRoute/DeltaStar.py
Four tweaks to delta debugging found while working on pathfinding:
1.  Write unreduced lines back out during within-line reduction.  This was mainly to ensure that the resulting sector files look ok, but doing this for full-line reduction sped up later within-line passes as well.
2. Unconditionally skip void subsectors during reduction, rather than only if half or more of all subsectors are void.
3. Add a noble-base-zone within-line reduction, to unstick a reduction that had gotten stuck.
4. Extract common bits of {sector,subsector,single-line,two-line} reducers into a common base class to square them up like the within-line passes already are.
> Delta debug tweaks

- PyRoute/AreaItems/Galaxy.py
- PyRoute/AreaItems/Sector.py
- PyRoute/DeltaDebug/DeltaDictionary.py
- PyRoute/DeltaDebug/DeltaGalaxy.py
- PyRoute/StatCalculation.py
- Tests/AreaItems/testAllegiance.py
- Tests/testDeltaReduce.py
Given stars, upon insertion, are added to their corresponding allegiance at galaxy, sector _and_ subsector levels, that suggests the following invariant:
World counts by allegiance at one level (galaxy, sector) should equal the _sum_ of the allegiance world counts of the areas at the next level down (sector, subsector).
Because integer equality is transitive (A == B and B == C implies A == C), don't need to compare galaxy level counts with sum of _subsector_ allegiance counts.
> Check allegiance world counts in is_well_formed()

- PyRoute/AreaItems/Galaxy.py
- PyRoute/DeltaDebug/DeltaDictionary.py
- PyRoute/DeltaDebug/DeltaGalaxy.py
- PyRoute/Inputs/ParseSectorInput.py
- Tests/AreaItems/testAllegiance.py
- Tests/Pathfinding/testTradeCalculation.py
- Tests/testDeltaReduce.py
Unify, as far as possible, sector-file read in both Galaxy and SectorDictionary.
Specifically, hoist out sector-file partitioning (into headers and lines) into a common ParseSectorInput method.
Similarly, hoist out allegiance and subsector parsing into dedicated ParseSectorInput methods.
> Tighten up sector reads in both Galaxy and SectorDictionary

- PyRoute/DeltaDebug/DeltaDebug.py
- PyRoute/DeltaDebug/DeltaDictionary.py
- PyRoute/DeltaDebug/DeltaReduce.py
- PyRoute/DeltaPasses/AllegianceReducer.py
- PyRoute/DeltaPasses/BaseLineReduce.py
- PyRoute/DeltaPasses/BaseTrimLineReduce.py
- PyRoute/DeltaPasses/IdentityLineReduce.py
- PyRoute/DeltaPasses/NoblesTrimLineReduce.py
- PyRoute/DeltaPasses/PortAndTlLineReduce.py
- PyRoute/DeltaPasses/SectorReducer.py
- PyRoute/DeltaPasses/SingleLineReducer.py
- PyRoute/DeltaPasses/SubsectorReducer.py
- PyRoute/DeltaPasses/TradeCodeLineReduce.py
- PyRoute/DeltaPasses/TradeCodeTrimLineReduce.py
- PyRoute/DeltaPasses/WithinLineReducer.py
- PyRoute/DeltaPasses/ZoneLineReduce.py
- PyRoute/DeltaPasses/ZoneTrimLineReduce.py
- PyRoute/DeltaStar.py
- PyRoute/Inputs/ParseSectorInput.py
- Tests/testDeltaDictionary.py
- Tests/testDeltaReduce.py
This PR started with adding an is_well_formed() check to SectorDictionary, to verify that each allegiance line in a sector file has at least one starline with that allegiance present, and that each starline maps to one of the present allegiance lines.
Additional changes along the way:
- Add trade-mp to reduction options;
- Unconditionally skip empty (sub) sectors;
- Remove empty allegiances from sector files when writing them out;
- Add bunch of within-line reduction passes;
- Fix existing within-line reduction passes to preserve interestingness;
> Delta debugging fixes

- .gitignore
- PyRoute/DeltaDebug/DeltaDebug.py
- PyRoute/DeltaDebug/actual_example.md
- PyRoute/DeltaDebug/readme.md
As it says on the tin, promote the allegiance-reduction pass from off-by-default to on-by-default, and update delta debugging docs to match.
> Promote allegiance-reduction pass to on-by-default
